# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Buffer

import flatbuffers

class BoolMatrix(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBoolMatrix(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BoolMatrix()
        x.Init(buf, n + offset)
        return x

    # BoolMatrix
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoolMatrix
    def N(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BoolMatrix
    def M(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BoolMatrix
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BoolMatrix
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def BoolMatrixStart(builder): builder.StartObject(3)
def BoolMatrixAddN(builder, n): builder.PrependInt32Slot(0, n, 0)
def BoolMatrixAddM(builder, m): builder.PrependInt32Slot(1, m, 0)
def BoolMatrixAddData(builder, data): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def BoolMatrixStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def BoolMatrixEnd(builder): return builder.EndObject()
