# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Buffers

import flatbuffers

class Spike(object):
    __slots__ = ['_tab']

    # Spike
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Spike
    def Address(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Spike
    def Timestamp(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateSpike(builder, address, timestamp):
    builder.Prep(4, 8)
    builder.PrependInt32(timestamp)
    builder.PrependInt32(address)
    return builder.Offset()
