# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Buffer

import flatbuffers

class IntegerArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntegerArray(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntegerArray()
        x.Init(buf, n + offset)
        return x

    # IntegerArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntegerArray
    def Column(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IntegerArray
    def ColumnLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            print "works"
            return self._tab.VectorLen(o)
        print "Fails"
        return 0

def IntegerArrayStart(builder): builder.StartObject(1)
def IntegerArrayAddColumn(builder, column): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(column), 0)
def IntegerArrayStartColumnVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IntegerArrayEnd(builder): return builder.EndObject()
