# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Buffer

import flatbuffers

class IntegerMatrix(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntegerMatrix(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntegerMatrix()
        x.Init(buf, n + offset)
        return x

    # IntegerMatrix
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntegerMatrix
    def N(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IntegerMatrix
    def M(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IntegerMatrix
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IntegerMatrix
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def IntegerMatrixStart(builder): builder.StartObject(3)
def IntegerMatrixAddN(builder, n): builder.PrependInt32Slot(0, n, 0)
def IntegerMatrixAddM(builder, m): builder.PrependInt32Slot(1, m, 0)
def IntegerMatrixAddData(builder, data): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def IntegerMatrixStartDataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IntegerMatrixEnd(builder): return builder.EndObject()
