# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Buffer

import flatbuffers

class SpikesArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSpikesArray(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpikesArray()
        x.Init(buf, n + offset)
        return x

    # SpikesArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpikesArray
    def List(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Spike import Spike
            obj = Spike()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SpikesArray
    def ListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SpikesArrayStart(builder): builder.StartObject(1)
def SpikesArrayAddList(builder, list): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(list), 0)
def SpikesArrayStartListVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SpikesArrayEnd(builder): return builder.EndObject()
